import React,{useEffect,useMemo,useState}from'react';import{Activity,AlertTriangle,Ambulance,ArrowRight,BarChart3,BrainCircuit,CheckCircle2,Clock3,Command,Database,Gauge,GitBranch,Layers3,MapPin,MessageSquare,Navigation,Radio,Route,ShieldCheck,Timer,Users,Wifi}from'lucide-react';import Map from'./components/Map';import{getJSON,postJSON,wsUrl}from'./lib/api';

type RouteT={id:string,name:string,eta_min:number,delay_min:number,uncertainty_min:number,risk:string,distance_km:number,points:any[],explanation:string};
type Rec={vehicle_id:string,current_eta_min:number,delay_min:number,cause:string,confidence:number,evidence:string[],routes:RouteT[],backup_vehicle_id:string|null,backup_eta_min:number|null};
const fallbackVehicle={id:'AMB-07',name:'AMB-07',status:'active',lat:12.9712,lon:77.594,speed_kmh:62,heading:72,hospital:'City General Hospital'};
export default function App(){
 const[vehicles,setVehicles]=useState<any[]>([]),[incidents,setIncidents]=useState<any[]>([]),[selected,setSelected]=useState('AMB-07'),[rec,setRec]=useState<Rec|null>(null),[live,setLive]=useState(false),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false),[activeTab,setActiveTab]=useState('overview'),[apiOffline,setApiOffline]=useState(false);
 useEffect(()=>{Promise.all([getJSON('/api/vehicles'),getJSON('/api/incidents')]).then(([v,i])=>{setVehicles(v);setIncidents(i);setApiOffline(false)}).catch(()=>{setVehicles([fallbackVehicle]);setIncidents([]);setApiOffline(true)});},[]);
 useEffect(()=>{const ws=new WebSocket(wsUrl('/ws/telemetry'));ws.onopen=()=>setLive(true);ws.onclose=()=>setLive(false);ws.onmessage=e=>{const d=JSON.parse(e.data);if(d.vehicle_id==='AMB-07')setVehicles(v=>v.map(x=>x.id==='AMB-07'?{...x,...d}:x))};return()=>ws.close()},[]);
 const vehicle=vehicles.find(v=>v.id===selected)||fallbackVehicle;
 const analyze=async()=>{setLoading(true);try{setRec(await getJSON(`/api/recommendations/${selected}`));setNotice('GeoAgent analysis complete · evidence refreshed')}catch(e){setNotice('API unavailable · showing the last known scenario')}finally{setLoading(false)}};
 useEffect(()=>{analyze()},[selected]);
 const act=async(action:string,route_id?:string)=>{try{await postJSON(`/api/vehicles/${selected}/actions`,{action,route_id});setNotice(action==='reroute'?'Reroute approval recorded in audit trail':action==='dispatch_backup'?'Backup dispatch request recorded':'Incident acknowledged')}catch(e){setNotice('Action could not be recorded · check the API connection')}};
 const routes=rec?.routes||[]; const recommended=routes.find(r=>r.id==='route-2')||routes[1];
 return <div className="app-shell">
  <header className="topbar"><div className="brand"><div className="brand-mark"><BrainCircuit/></div><div><b>GeoAgentic</b><span>Emergency Response Copilot</span></div></div><div className="top-status"><span className="live-dot"/> SYSTEM ONLINE <span className="sep"/> <Wifi size={14}/> {live?'LIVE TELEMETRY':'REPLAY MODE'} <span className="sep"/> <span>Control Room 01</span></div><button className="user"><div>BK</div><span>Dispatcher</span></button></header>
  <div className="layout">
  <aside className="sidebar"><nav>{[['overview','Overview',Activity],['vehicles','Vehicles',Ambulance],['incidents','Incidents',AlertTriangle],['routes','Routes',Route],['fleet','Fleet',Users],['audit','Audit Trail',Database]].map(([id,label,Icon]:any)=><button key={id} className={activeTab===id?'active':''} onClick={()=>{setActiveTab(id);document.getElementById(`section-${id}`)?.scrollIntoView({behavior:'smooth',block:'start'})}}><Icon size={18}/><span>{label}</span>{id==='vehicles'&&<em>{vehicles.length||3}</em>}{id==='incidents'&&<em className="danger">{incidents.length||3}</em>}</button>)}</nav><div className="side-bottom"><div className="health"><span className={apiOffline?'amber':'green'}/><div><b>{apiOffline?'Replay mode':'All systems'}</b><small>{apiOffline?'API unavailable':'Operational'}</small></div></div><small className="version">v2.0 · Control plane</small></div></aside>
   <main className="main">
    <div id="section-overview" className="page-head"><div><div className="eyebrow"><Radio size={14}/> REAL-TIME DECISION SUPPORT</div><h1>Emergency Response Command</h1><p>Monitor movement, diagnose disruptions and review evidence-backed actions.</p></div><div className="head-actions"><button className="ghost" onClick={analyze} disabled={loading}><Activity size={16}/>{loading?'Analyzing…':'Refresh analysis'}</button><button className="primary" onClick={()=>act('acknowledge')}><CheckCircle2 size={16}/>Acknowledge incident</button></div></div>
    {(notice||apiOffline)&&<div className={`notice ${apiOffline?'warning':''}`}><CheckCircle2 size={16}/>{apiOffline?'API unavailable · replaying the seeded command scenario':notice}<button onClick={()=>setNotice('')}>×</button></div>}
    <section id="section-fleet" className="metrics"><Metric icon={Ambulance} label="Active Units" value="1" sub="2 available"/><Metric icon={AlertTriangle} label="Active Incidents" value={String(incidents.length||3)} sub="1 high severity" danger/><Metric icon={Timer} label="Current Delay" value={rec?`+${rec.delay_min.toFixed(1)}m`:'—'} sub="AMB-07"/><Metric icon={Gauge} label="System Latency" value="1.8s" sub="within target"/></section>
    <section id="section-vehicles" className="workspace">
      <div id="section-incidents" className="map-card"><div className="card-head"><div><b>Live Operations Map</b><span>Planned · current · recommended routes</span></div><div className="legend"><i className="blue"/>Planned <i className="red"/>Delayed <i className="greenline"/>Recommended</div></div><Map vehicle={vehicle} incidents={incidents} routes={routes}/><div className="map-overlay"><div><small>Current Vehicle</small><strong>{vehicle.name}</strong><span><span className="green-dot"/> {vehicle.status}</span></div><div><small>Speed</small><strong>{Math.round(vehicle.speed_kmh)} km/h</strong></div><div><small>ETA</small><strong className="red-text">{rec?.current_eta_min.toFixed(1)||'17.2'} min</strong></div></div></div>
      <aside className="copilot-card"><div className="copilot-head"><div className="agent-icon"><BrainCircuit/></div><div><b>GeoAgent</b><span>Evidence-grounded analysis</span></div><span className="confidence">{rec?Math.round(rec.confidence*100):82}%</span></div><div className="query"><Command size={15}/><span>{loading?'Running analysis…':'Analyze AMB-07 situation'}</span><ArrowRight size={15}/></div><div className="diagnosis"><div className="diag-icon"><AlertTriangle/></div><div><small>Likely cause</small><h3>{rec?.cause||'Accident on Main St.'}</h3><p>Confidence {rec?rec.confidence.toFixed(2):'0.82'}</p></div></div><div className="evidence"><b><ShieldCheck size={15}/> Evidence</b>{(rec?.evidence||['Traffic speed dropped 68%','Incident detected 220m ahead','Lane closure reported']).map((x,i)=><div key={i}><span>✓</span>{x}</div>)}</div><div className="recommend"><div className="rec-title"><CheckCircle2 size={18}/><div><b>Recommended action</b><small>Reroute current unit</small></div></div><div className="rec-main"><span>{recommended?.name||'Alternative 1'}</span><strong>{recommended?.eta_min?.toFixed(1)||'11.4'} min</strong><em>↓ 5.8 min</em></div><p>Alternative route avoids the incident corridor and has lower predicted risk.</p><div className="actions"><button className="primary" disabled={loading} onClick={()=>act('reroute',recommended?.id)}><Navigation size={15}/>Approve reroute</button><button className="secondary" disabled={loading} onClick={()=>act('dispatch_backup')}><Ambulance size={15}/>Dispatch {rec?.backup_vehicle_id||'AMB-12'}</button></div></div></aside>
    </section>
    <section id="section-routes" className="lower-grid"><div className="panel"><div className="panel-title"><div><b>Route Comparison</b><span>ETA · delay · uncertainty · incident risk</span></div><Route size={18}/></div><div className="table"><div className="tr th"><span>Route</span><span>ETA</span><span>Δ Delay</span><span>Uncertainty</span><span>Risk</span></div>{routes.map((r,i)=><div className={`tr ${i===1?'selected':''}`} key={r.id}><span><i className={`route-dot r${i}`}/>{r.name}</span><strong>{r.eta_min.toFixed(1)}m</strong><span className={r.delay_min<0?'good':'bad'}>{r.delay_min>0?'+':''}{r.delay_min.toFixed(1)}m</span><span>±{r.uncertainty_min.toFixed(1)}m</span><b className={`risk ${r.risk}`}>{r.risk}</b></div>)}</div></div><div id="section-audit" className="panel"><div className="panel-title"><div><b>Decision Trace</b><span>Detect → Diagnose → Predict → Recommend</span></div><GitBranch size={18}/></div><div className="trace">{[['Detect','Route deviation identified',MapPin],['Diagnose',rec?.cause||'Incident-induced disruption',AlertTriangle],['Predict',`${rec?.current_eta_min?.toFixed(1)||'17.2'} min current ETA`,Clock3],['Recommend',`${recommended?.eta_min?.toFixed(1)||'11.4'} min alternative`,CheckCircle2]].map(([a,b,I]:any,i)=><div className="trace-row" key={a}><div className="trace-num">{i+1}</div><I size={17}/><div><b>{a}</b><span>{b}</span></div><small>{i===3?'Ready':'Complete'}</small></div>)}</div></div></section>
    <footer><span><Layers3 size={14}/> Modular architecture</span><span><BrainCircuit size={14}/> GeoAgent orchestrates specialized tools</span><span><ShieldCheck size={14}/> Human-in-the-loop</span><span><Database size={14}/> PostgreSQL audit trail</span></footer>
   </main>
  </div>
 </div>
}
function Metric({icon:Icon,label,value,sub,danger=false}:any){return <div className="metric"><div className={`metric-icon ${danger?'danger-bg':''}`}><Icon size={19}/></div><div><small>{label}</small><strong className={danger?'red-text':''}>{value}</strong><span>{sub}</span></div></div>}
